---
# roles/bash/tasks/main.yml

- name: "Copy files."
  copy:
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0444"
    src: "{{ item.src }}"
    backup: yes
  with_items: "{{ bash_files }}"
