---
# roles/postman/tasks/debian.yml

- name: "Debian | Download archive."
  get_url:
    url: "https://dl.pstmn.io/download/latest/linux64"
    dest: "{{ downloads_dir }}/postman.tgz"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: '0644'

- name: "Debian | Extract archive."
  unarchive:
    src: "{{ downloads_dir }}/postman.tgz"
    dest: "/opt/"
  become: true

- name: "Debian | Link the executable."
  file:
    path: "/usr/local/bin/postman"
    state: "link"
    src: "/opt/Postman/app/Postman"
  become: true

- name: "Debian | Desktop launcher."
  copy:
    dest: "/usr/share/applications/postman.desktop"
    src: "postman.desktop"
  become: true
