---
# site.yml
- name: "c60"
  hosts: c60
  connection: local
  become: false
  roles:
    - { role: "common", tags: "common" }
    - { role: "ansible", tags: "ansible" }
    - { role: "aws", tags: "aws" }
    - { role: "bash", tags: "bash" }
    - { role: "docker", tags: "docker" }
    - { role: "sound", tags: "sound" }
    - { role: "clementine", tags: "clementine" }
    - { role: "vlc", tags: "vlc" }
    - { role: "gcloud", tags: "gcloud" }
    - { role: "intellij", tags: "intellij" }
    - { role: "kubernetes", tags: [ "kubernetes", "k8s" ] }
    - { role: "lastpass", tags: "lastpass" }
    - { role: "packer", tags: "packer" }
    - { role: "postgres", tags: [ "postgresql", "postgres" ] }
    - { role: "slack", tags: "slack" }
    - { role: "postman", tags: "postman" }
    - { role: "fonts", tags: "fonts" }
    - { role: "terraform", tags: "terraform" }
    - { role: "vagrant", tags: "vagrant" }
    - { role: "vim", tags: "vim" }
    - { role: "vivaldi", tags: "vivaldi" }
    - { role: "tmux", tags: "tmux" }
    - { role: "bittorrent", tags: [ "bittorrent", "torrent"] }
    - { role: "dotfiles", tags: "dotfiles" }

- name: "nuc"
  hosts: nuc
  connection: ssh
  become: false
  roles:
    - { role: "common", tags: "common" }
    - { role: "bash", tags: "bash" }
    - { role: "docker", tags: "docker" }
    - { role: "tmux", tags: "tmux" }
    - { role: "plex", tags: "plex" }
    - { role: "bittorrent", tags: [ "bittorrent", "torrent"] }

- name: "8wp"
  hosts: 8wp
  connection: local
  become: false
  roles:
    - { role: "common", tags: "common" }
    - { role: "bash", tags: "bash" }
    - { role: "ansible", tags: "ansible" }
    - { role: "aws", tags: "aws" }
    - { role: "docker", tags: "docker" }
    - { role: "dotfiles", tags: "dotfiles" }
    - { role: "gcloud", tags: "gcloud" }
    - { role: "intellij", tags: "intellij" }
    - { role: "kubernetes", tags: [ "kubernetes", "k8s" ] }

- name: "v2r"
  hosts: v2r
  connection: local
  become: false
  roles:
    - { role: "common", tags: "common" }
    - { role: "1password", tags: "1password" }
    - { role: "ansible", tags: "ansible" }
    - { role: "aws", tags: "aws" }
    - { role: "bash", tags: "bash" }
    - { role: "datagrip", tags: "datagrip" }
    - { role: "docker", tags: "docker" }
    - { role: "dotfiles", tags: "dotfiles" }
    - { role: "dropbox", tags: "dropbox" }
    - { role: "evernote", tags: "evernote" }
    - { role: "fonts", tags: "fonts" }
    - { role: "gcloud", tags: "gcloud" }
    - { role: "golang", tags: "golang" }
    - { role: "google-backup", tags: "google-backup" }
    - { role: "gimp", tags: "gimp" }
    - { role: "git", tags: "git" }
    - { role: "insomnia", tags: "insomnia" }
    - { role: "intellij", tags: "intellij" }
    - { role: "iterm2", tags: "iterm2" }
    - { role: "java", tags: "java" }
    - { role: "kindle", tags: "kindle" }
    - { role: "kubernetes", tags: [ "kubernetes", "k8s" ] }
    - { role: "lastpass", tags: "lastpass" }
    - { role: "oath", tags: "oath" }
    - { role: "packer", tags: "packer" }
    - { role: "parallels", tags: "parallels" }
    - { role: "postman", tags: "postman" }
    - { role: "resize", tags: "resize" }
    - { role: "shell-utils", tags: "shell-utils" }
    - { role: "slack", tags: "slack" }
    - { role: "spectacle", tags: "spectacle" }
    - { role: "spotify", tags: "spotify" }
    - { role: "steam", tags: "steam" }
    - { role: "tcpdump", tags: "tcpdump" }
    - { role: "terraform", tags: ["terraform", "tf"] }
    - { role: "vagrant", tags: "vagrant" }
    - { role: "vim", tags: "vim" }
    - { role: "virtualbox", tags: "virtualbox" }
    - { role: "vivaldi", tags: "vivaldi" }
    - { role: "vmware", tags: "vmware" }
    - { role: "wireshark", tags: "wireshark" }

#TODO: replace common with regular roles
#TODO: move dotifles resources to other roles
