---
# roles/terraform/defaults/main.yml

terraform_installdir: "/opt/HashiCorp"
terraform_url: "https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip"

packages:
  macosx:
    formulae:
      - terraform
      - terraform-inventory
      - terraform-docs
      - terraforming
