---
# roles/common/defaults/main.yml

packages:
  debian:
    - apt-config-auto-update
    - aptitude
    - curl
    - dnsutils
    - mlocate
    - shellcheck
    - tree
  macosx:
    formulae:
      - curl
      - htop
      - shellcheck
      - tree
