---
# roles/docker/defaults/main.yml

prerequisites:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - wget

packages:
  fedora:
    - docker
    - docker-compose
  debian:
    - docker-ce
    - docker-compose
  macosx:
    formulae:
      - docker
      - docker-compose
    casks:
      - docker
