---
# roles/vagrant/tasks/macosx.yml

- name: "MacOS | packages"
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.macosx.formulae }}"

- name: "MacOS | casks"
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.macosx.casks }}"
