---
# roles/vagrant/tasks/macosx.yml

- name: "MacOS | Install packages."
  package:
    name: "{{ packages_macosx }}"
    state: latest
  tags:
    - packages

- name: "MacOS | Install Desktop apps."
  homebrew_cask:
    name: "{{ packages_macosx_casks }}"
    state: latest
  tags:
    - packages
    - casks