---
# roles/dotfiles/tasks/main.yml

- name: "Misc. config files."
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0444"
  with_items: "{{ dotfiles }}"
