---
# roles/dotifles/tasks/main.yml

- name: "{{ role_path | basename ||: Copy misc. config files."
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0444"
  with_items: "{{ dotfiles }}"
