---
# roles/intellij/tasks/main.yml

- name: "Main | OS-specific includes."
  include: "{{ ansible_distribution | lower }}.yml"

- name: "Main | File copies."
  copy:
    dest: "{{ homedir }}/.ideavimrc"
    src: "ideavimrc"
