---
# roles/kubernetes/tasks/debian.yml

- name: "MacOS | Install packages."
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.macosx.formulae }}"

- name: "MacOS | Install casks."
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.macosx.casks }}"
