---
# roles/ansible/tasks/debian.yml

# This doesn't really work because 2.4 is needed to properly filter the vars
# so it needs to be manually installed before these plays are run anyway.
- name: "debian | ppa repository"
  apt_repository:
    repo: "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"
    state: present
    filename: ansible
  become: true

- name: "Debian | Install packages."
  package:
    name: "{{ item }}"
    state: latest
    allow_unauthenticated: yes
  become: true
  with_items: "{{ packages.debian }}"
