---
# roles/ansible/tasks/main.yml

- name: "Main | OS-specific includes."
  include: "{{ ansible_distribution | lower }}.yml"

- name: ".ansible.cfg"
  copy:
    dest: "{{ homedir }}/.ansible.cfg"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: '0444'
    src: "ansible.cfg"
    force: true
    backup: yes

- name: "inventory file."
  copy:
    dest: "/etc/ansible/hosts"
    mode: '0444'
    src: "inventory.yml"
    force: true
    backup: yes
  become: true

- name: "Clean up playbook.retry files."
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ homedir }}/playbook.retry"
    - "{{ homedir }}/ansible/site.retry"
