---
# roles/ansible/tasks/main.yml

- name: "Debian tasks."
  import_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "MacOS tasks."
  import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'

- name: ".ansible.cfg"
  copy:
    dest: "{{ homedir }}/.ansible.cfg"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: '0444'
    src: "ansible.cfg"
    force: true
    backup: yes

- name: "inventory file."
  copy:
    dest: "/etc/ansible/hosts"
    mode: '0444'
    src: "inventory.yml"
    force: true
    backup: yes
  become: true

- name: "Clean up playbook.retry files."
  file:
    path: "{{ homedir }}/playbook.retry"
    state: "absent"
