---
# roles/vivaldi/tasks/fedora.yml

- name: "Fedora | Add EPEL repository."
  yum_repository:
    name: epel
    description: EPEL yum repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  become: true

- name: "Fedora | Add Vivaldi repository."
  yum_repository:
    name: vivaldi
    description: Vivaldi yum repo
    baseurl: https://repo.vivaldi.com/stable/rpm/x86_64/
  become: true

- name: "Fedora | Install packages."
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ packages.fedora }}"
