#!/usr/bin/env bash
# .bashrc

umask 022

EDITOR="$(command -v vim || command -v vi)" && export EDITOR
export HISTCONTROL=ignoreboth
export HISTFILESIZE=10000
export HISTSIZE=10000
export SDKMAN_DIR="${HOME}/.sdkman"
export SPEC_OPTS="--format documentation"
export SSLKEYLOGFILE="${HOME}/.sslkeylogfile"
export SVN_EDITOR=/usr/bin/vim
export VAGRANT_DEFAULT_PROVIDER='virtualbox'
export brofist="👊"
export shrug="¯\\_(ツ)_/¯"
export thumbsup="👍"

if command -v vimpager &>/dev/null; then
    if [[ -f ${HOME}/.vimpagerrc ]]; then
        export PAGER="vimpager -u ${HOME}/.vimpagerrc"
    else
        export PAGER="vimpager"
    fi
fi

shopt -s checkwinsize
shopt -s histappend

source "${HOME}/.bash_functions.sh"

do_set_aliases

pathmunge /opt/JetBrains/bin after
pathmunge /opt/HashiCorp after
pathmunge "${HOME}/.local/bin" after
pathmunge "${HOME}/bin" after

xrdb -merge ~/.Xresources 2>/dev/null || true

for i in \
    "${HOME}/.credentials.sh" \
    "${HOME}/.sdkman/bin/sdkman-init.sh" \

do
    [[ -s "${i}" ]] && source "${i}"
done

if is_interactive; then
    do_set_dir_colors
    do_set_less_termcaps
    do_set_sparks
    do_set_tputs
    complete -C /usr/local/bin/aws_completer aws

    for i in \
        "${HOME}/.bash_prompt.sh" \
        "${HOME}/.iterm2_shell_integration.bash" \
        "${HOME}/.kube/kubectl-completion.sh" \
        "/opt/google/google-cloud-sdk/completion.bash.inc" \
        "/usr/local/etc/bash_completion" \

    do
        [[ -s "${i}" ]] && source "${i}"
    done  # end for i in interactive source files

    case "${ITERM_PROFILE}" in
        JMFS*)
            JAVA_HOME=$(/usr/libexec/java_home -v 1.8 )&& export JAVA_HOME
            AWS_PROFILE="jmfs.jpuellmann" && export AWS_PROFILE
            ;;
        WWT)
            AWS_PROFILE="wwt.jpuellma" && export AWS_PROFILE
            ;;
        Personal)
            AWS_PROFILE="personal.jpuellma" && export AWS_PROFILE
            ;;
        DEs)
            AWS_PROFILE="asynchrony.des.james.puellmann" && export AWS_PROFILE
            ;;
        *)
            AWS_PROFILE="" && export AWS_PROFILE
            ;;
    esac  # end case "${ITERM_PROFILE}
fi  # end if is_interactive
