#!/usr/bin/env bash
# .bashrc
umask 022

export BROWSER="/usr/bin/google-chrome --user-data-dir=${HOME}/.config/man"
export EDITOR="/usr/bin/vim"
export GOPATH="${HOME}/Go"
export HISTCONTROL=ignoreboth
export HISTFILESIZE=10000
export HISTSIZE=10000
export SPEC_OPTS="--format documentation"
export SSLKEYLOGFILE="${HOME}/.sslkeylogfile"
export SVN_EDITOR=/usr/bin/vim
export VAGRANT_DEFAULT_PROVIDER='virtualbox'
export brofist="👊"
export rvm_path="${HOME}/.rvm"
export shrug="¯\\_(ツ)_/¯"
export thumbsup="👍"

shopt -s checkwinsize
shopt -s histappend

# shellcheck source=/dev/null
source "${HOME}/.bash_functions.sh"

# shellcheck source=/dev/null
source "${HOME}/.bash_prompt.sh"

do_set_aliases
do_set_dir_colors
do_set_less_termcaps
do_set_sparks
do_set_tputs

pathmunge "${GOPATH}:${GOPATH}/bin" after
pathmunge "${HOME}/.rvm/bin" after
pathmunge /opt/JetBrains/bin after
pathmunge /opt/HashiCorp after
pathmunge "${HOME}/anaconda3/bin" before

complete -C /usr/local/bin/aws_completer aws

xrdb -merge ~/.Xresources 2>/dev/null || true

# shellcheck source=/dev/null
source ${HOME}/.credentials.sh 2>/dev/null || true

if (which kubectl >/dev/null); then
# shellcheck source==/dev/null
    source <(kubectl completion bash)
fi
