---
# roles/docker/tasks/debian.yml

- name: "Debian | Install prerequisites."
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ prerequisites }}"

- name: "Debian | Apt gpg key"
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
  become: true

- name: "Debian | .deb repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present
    filename: "docker"
  become: true

- name: "Debian | Install packages."
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ packages.debian }}"

- name: "Debian | Enable service."
  service:
    name: "docker"
    state: "started"
    enabled: true
  become: true

- name: "Debian | Add {{ username }} to docker group."
  user:
    name: "{{ username }}"
    groups: "docker"
    append: true
  become: true
