---
# roles/docker/tasks/macos.yml

- name: "MacOS | Package install."
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.macosx.formulae }}"

- name: "MacOS | Docker desktop app install"
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.macosx.casks }}"
