---
# roles/docker/tasks/main.yml

- name: "{{ role_path | basename }}: package install."
  package:
    name: "docker-engine"
    state: latest
  become: true
  tags:
  - packages

- name: "{{ role_path | basename }}: Enable service."
  service:
    name: "docker"
    state: "started"
    enabled: true
  become: true
  tags:
  - services

- name: "{{ role_path | basename }}: Add {{ username }} to docker group."
  user:
    name: "{{ username }}"
    groups: "docker"
    append: true
  become: true
  tags:
  - users
  - groups
