---
# roles/vim/tasks/macosx.yml

- name: "install package."
  package:
    name: vim
    state: latest
  tags:
    - packages

- name: "Install desktop app."
  homebrew_cask:
    name: macvim
    state: latest
  tags:
    - packages
    - casks
