---
# roles/plex/tasks/debian.yml

- name: "prerequisite packages."
  package:
    name: "apt-transport-https"
    state: latest
  become: true

- name: "apt repo key"
  apt_key:
    url: "https://downloads.plex.tv/plex-keys/PlexSign.key"
    state: present
  become: true

- name: "apt repo"
  apt_repository:
    repo: "deb https://downloads.plex.tv/repo/deb ./public main"
    state: present
    filename: plex
  become: true

- name: "Install packages."
  package:
    name:
      - plexmediaserver
    state: latest
  become: true

- name: "service"
  service:
    name: "plexmediaserver"
    state: started
    enabled: true
  become: true
