---
# roles/plex/tasks/debian.yml

- name: "Debian | prerequisite packages."
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ prereequisites }}"

- name: "Debian | apt repo key"
  apt_key:
    url: "https://downloads.plex.tv/plex-keys/PlexSign.key"
    state: present
  become: true

- name: "Debian | apt repo"
  apt_repository:
    repo: "deb https://downloads.plex.tv/repo/deb ./public main"
    state: present
    filename: plex
  become: true

- name: "Debian | Install packages."
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ prereequisites }}"

- name: "Debian | service"
  service:
    name: "plexmediaserver"
    state: started
    enabled: true
  become: true
