---
# roles/fonts/tasks/macosx.yml

- name: "MacOS | Install homebrew fonts"
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages.macosx.casks }}"

- name: "MacOS | Download Source Code pro Fonts from Adobe"
  get_url:
    dest: "{{ downloads_dir }}"
    url: "{{ source_code_pro_font_url }}"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: '0644'
  become: true
